services:
  qashare:
    image: ghcr.io/pranaovs/qashare:main
    container_name: qashare
    restart: always
    expose:
      - "8080"
    environment:
      - DB_URL=postgres://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@postgres:5432/${DB_NAME:-qashare}
      - GIN_MODE=release
      - API_PUBLIC_URL=https://qashare.pranaovs.me
    env_file:
      - .env
    depends_on:
      - postgres

    labels:
      # Traefik
      - "traefik.enable=true"

      - "traefik.http.routers.qashare-https.rule=Host(`qashare.pranaovs.me`)"
      - "traefik.http.routers.qashare-https.entrypoints=websecure"
      - "traefik.http.routers.qashare-https.service=qashare"

      - "traefik.http.routers.qashare-ts.rule=Host(`qashare.devserver.ts.net`) || Host(`qashare.devserver`)"
      - "headnscale.subdomain=qashare"
      - "traefik.http.routers.qashare-ts.entrypoints=web"
      - "traefik.http.routers.qashare-ts.service=qashare"

      - "traefik.http.services.qashare.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik_net"
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Podman Auto-Update
      - "io.containers.autoupdate=registry"
    networks:
      - default
      - traefik_net

  nginx-download:
    image: nginx:alpine
    container_name: qashare-nginx-download
    restart: always
    expose:
      - "80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro,Z
      - ./app:/app:ro,Z
    labels:
      # Traefik
      - "traefik.enable=true"

      - "traefik.http.routers.qashare-download-https.rule=Host(`qashare.pranaovs.me`) && PathPrefix(`/download`)"
      - "traefik.http.routers.qashare-download-https.entrypoints=websecure"
      - "traefik.http.routers.qashare-download-https.service=qashare-download"
      - "traefik.http.routers.qashare-download-https.priority=10"

      - "traefik.http.routers.qashare-download-ts.rule=(Host(`qashare.devserver.ts.net`) || Host(`qashare.devserver`)) && PathPrefix(`/download`)"
      - "traefik.http.routers.qashare-download-ts.entrypoints=web"
      - "traefik.http.routers.qashare-download-ts.service=qashare-download"
      - "traefik.http.routers.qashare-download-ts.priority=10"

      - "traefik.http.services.qashare-download.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_net"
    networks:
      - traefik_net

  postgres:
    image: postgres:18-alpine
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-qashare}
    volumes:
      - ./data:/var/lib/postgresql:Z,U
    networks:
      - default

networks:
  traefik_net:
    external: true
