#!/usr/bin/env sh

HOOK_DIR="$(dirname "$0")/$(basename "$0").d"

if [ -d "$HOOK_DIR" ]; then
  for script in "$HOOK_DIR"/*; do
    if [ -x "$script" ]; then
      echo "Running $(basename "$0" | sed 's/-/ /g') hook: $(basename "$script")"
      "$script"
    fi
  done
fi
