services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      - "30086:80/tcp" # Default HTTP Port
    dns:
      - 9.9.9.9
      - 1.1.1.1
    environment:
      TZ: "Asia/Kolkata"
      FTLCONF_webserver_api_password: "" # Password not needed (not exposed)
      FTLCONF_dns_listeningMode: "all" # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
      FTLCONF_dns_upstreams: "9.9.9.9;1.1.1.1;8.8.8.8;8.8.4.4"
    volumes:
      - "./etc-pihole:/etc/pihole"
    cap_add:
      - SYS_NICE
    restart: always
