services:
  archiveTeamWarrior:
    image: atdr.meo.ws/archiveteam/warrior-dockerfile
    container_name: archiveTeamWarrior
    hostname: archiveTeamWarrior
    ports:
      - "30082:8001"
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      # AutoKuma (uptime-kuma)
      - "kuma.archiveteam.group.name=Archive Team Warrior"
      - "kuma.archiveteam.docker.name=archiveTeamWarrior (container)"
      - "kuma.archiveteam.docker.docker_container=archiveTeamWarrior"
      - "kuma.archiveteam.docker.docker_host_name=local"
      - "kuma.archiveteam.docker.parent_name=archiveteam.group"
    restart: unless-stopped
    volumes:
      - "./config.json:/home/warrior/projects/config.json"
      - "warrior_data:/home/warrior/data"
      - "warrior_projects:/home/warrior/projects"

volumes:
  warrior_data:
  warrior_projects:
