services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    ports:
      - "30088:5678"
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_PORT=5678
      - N8N_SECURE_COOKIE=false
      - NODE_ENV=production
      - TZ=Asia/Kolkata
    volumes:
      - ./n8n_data:/home/node/.n8n
