http:
  routers:
    http-catchall:
      rule: "HostRegexp(`^.+$`)"
      entryPoints:
        - web
      middlewares:
        - https-redirect
      service: noop@internal
      priority: 1

  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true

    hsts:
      headers:
        stsSeconds: 86400
        stsIncludeSubdomains: true
        stsPreload: false

    nosniff:
      headers:
        contentTypeNosniff: true

    frame-options:
      headers:
        customFrameOptionsValue: SAMEORIGIN

    referrer-policy:
      headers:
        referrerPolicy: "strict-origin-when-cross-origin"
