server {
    listen 80;
    root /app;

    location ~ ^/download {
        default_type application/vnd.android.package-archive;
        add_header Content-Disposition 'attachment; filename="qashare.apk"';
        try_files /qashare.apk =404;
    }
}
