services:
  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    volumes:
      - ./StirlingPDF/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - ./StirlingPDF/extraConfigs:/configs
      - ./StirlingPDF/customFiles:/customFiles/
      - ./StirlingPDF/pipeline:/pipeline/
    environment:
      - DISABLE_ADDITIONAL_FEATURES=false
      - LANGS=en_US
    labels:
      - "lazytainer.group=stirlingpdf"
      - "com.centurylinklabs.watchtower.enable=true"
    network_mode: service:lazytainer
    restart: unless-stopped

  lazytainer:
    container_name: lazytainer-stirling-pdf
    image: ghcr.io/vmorganp/lazytainer:master
    environment:
      VERBOSE: false
    ports:
      - "30085:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "lazytainer.group.stirlingpdf.ports=8080"
      - "lazytainer.group.stirlingpdf.minPacketThreshold=2"
      - "lazytainer.group.stirlingpdf.inactiveTimeout=300"
      - "com.centurylinklabs.watchtower.enable=true"
    security_opt:
      - label=type:spc_t
    restart: always
