services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime_kuma
    restart: unless-stopped
    ports:
      - "30090:3001"
    security_opt:
      - label=type:spc_t
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/app/data
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.uptime_kuma.rule=Host(`status.pranaovs.me`) || Host(`uptime.pranaovs.me`)"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.services.uptime_kuma.loadbalancer.server.port=3001"
      - "traefik.http.routers.uptime_kuma.entrypoints=websecure"
      - "traefik.http.routers.uptime_kuma.tls=true"
      - "traefik.http.routers.uptime_kuma.tls.certresolver=le"
      # AutoKuma (uptime-kuma)
      - "kuma.__docker_host__.local.connection_type=socket"
      - "kuma.__docker_host__.local.path=/var/run/docker.sock"
      - "kuma.uptime_kuma.group.name=Uptime Kuma"
      - "kuma.uptime_kuma.http.0.name=Uptime Kuma (status.pranaovs.me)"
      - "kuma.uptime_kuma.http.0.url=https://status.pranaovs.me"
      - "kuma.uptime_kuma.http.0.parent_name=uptime_kuma.group"
      - "kuma.uptime_kuma.http.1.name=Uptime Kuma (uptime.pranaovs.me)"
      - "kuma.uptime_kuma.http.1.url=https://uptime.pranaovs.me"
      - "kuma.uptime_kuma.http.1.parent_name=uptime_kuma.group"
      - "kuma.uptime_kuma.docker.name=uptime_kuma (container)"
      - "kuma.uptime_kuma.docker.docker_container=uptime_kuma"
      - "kuma.uptime_kuma.docker.docker_host_name=local"
      - "kuma.uptime_kuma.docker.parent_name=uptime_kuma.group"
    networks:
      - default
      - traefik_net

  autokuma:
    image: ghcr.io/bigboot/autokuma:latest
    restart: unless-stopped
    environment:
      AUTOKUMA__KUMA__URL: http://uptime_kuma:3001
    env_file: ".env"
    security_opt:
      - label=type:spc_t
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/data
    labels:
      # AutoKuma (uptime-kuma)
      - "kuma.autokuma.docker.name=autokuma (container)"
      - "kuma.autokuma.docker.docker_container=autokuma"
      - "kuma.autokuma.docker.docker_host_name=local"
      - "kuma.autokuma.docker.parent_name=uptime_kuma.group"

networks:
  traefik_net:
    external: true
