services:
  shadowbox:
    image: quay.io/outline/shadowbox:stable
    container_name: shadowbox
    restart: unless-stopped
    ports:
      - "${SB_KEYS_PORT}:${SB_KEYS_PORT}/udp"   # Access key port (UDP)
    #   - "${SB_API_PORT}:${SB_API_PORT}/tcp"   # Management API
    #   - "${SB_KEYS_PORT}:${SB_KEYS_PORT}/tcp"   # Access key port (TCP)
    environment:
      - SB_STATE_DIR=/data
      - SB_API_PORT=${SB_API_PORT}
      - SB_API_PREFIX=${SB_API_PREFIX}
      - SB_CERTIFICATE_FILE=/data/shadowbox-selfsigned.crt
      - SB_PRIVATE_KEY_FILE=/data/shadowbox-selfsigned.key
    volumes:
      - ./data:/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  default:
    name: caddy_net
    external: true

